### ISSUE TITLE
Why is this a separate repo?

### ISSUE THREAD

**Issue by alcuadrado** [sorpaas/rust-evm-tests#1]
Hi @sorpaas,

I'm starting to read through the `rust-evm` code and trying to understand its architecture. Most of my experience with the EVM comes from collaborating in https://github.com/ethereumjs/ethereumjs-vm, and yours is pretty different.

I thought that the standard json tests runner would be a good place to look at as an example of how to use it, and took me a while to find this repo.

I wonder why this is in a separate repo. Because of the size of the tests? Or it this something common in rust? I'm totally new to the language.

Thanks,
Patricio

**Comment by sorpaas** [comment]
Hi @alcuadrado! The reason why this is a separate repo is because testing needs to use some crates in Parity Ethereum / Open Ethereum, which is licensed under GPL. Two repos make sure we don't have any license violations.

**Comment by alcuadrado** [comment]
Makes sense. Thanks for your answer!
